### ISSUE TITLE
Favorite subscriptions

### ISSUE THREAD

**Issue by wizzomafizzo** [wizzomafizzo/MiSTer_Favorites#10]
@therourke

I've been thinking about this more and if you're willing to get involved with the implementation I'd like to try put something together. I reckon the favorites scripts might be the best place to to do it, just because I already have a boot script that runs to refresh symlinks.

I'm imagining a thing where people write out and publish their own "best of" games lists or whatever. You add them to this script. On boot it scrapes all the lists and then arranges a folder of favorites to match it.

Maybe something like:

https://github.com/wizzomafizzo/MiSTer_Favorites/my_awesome_games.json

And inside:
```
[
  { name: "SMB3", system: "SNES", filename: "smb3 (u).rom", checksum: "1h2j3g12jh3g" },
  ... and so on
]
```

Does that make sense? It will take some work to get it functioning properly but I think you're onto something.

**Comment by therourke** [comment]
Hello... this sounds fun. How can I help/be involved?

Something like this would need a community led aspect. Like a new themed list every month or something. It could at first be updated according to 'best ever shmups' or something like that. But the opportunity to ask people to curate lists themselves would be exciting. You could ask leading members of the MiSTer community to choose their top ten games, top ten gems, or something like that. Would be an amazing way to promote the MiSTer community, and put the focus firmly back onto the games themselves.

**Comment by wizzomafizzo** [comment]
I think you've got the idea. I can make a technical implementation of the idea, but I'm not really interested personally in making any of these lists or going out to the community to get people involved. If that's something you'd like to do then that's where I would definitely appreciate some help

Here is a draft idea I had for the subscription file you would maintain as someone making a list:
```
name = Discord Games of the Month
author = Discord Community
url = https://github.com/wizzomafizzo/MiSTer_Favorites/games_of_the_month.ini
updated = 2022-09-01

[Crysalis]
system = NES
file = Crysalis (USA)

[McDonald's Treasure Land Adventure]
system = Genesis
file = McDonald's Treasure Land Adventure (USA)

[Vagrant Story]
system = PSX
file = Vagrant Story (USA)|Vagrant Story
```

Does this make sense? It seems easy enough to maintain as a non-technical person? It will require changes as we build the feature but that's the gist of it. Matching filenames will properly will be a challenge (perhaps we can look into  checksums as well). 

This file goes in a folder on your mister and the script will populate that folder with the listed games. Each boot it checks if it should download a new version of the list. If a game can't be found on your system, maybe we can make a fake (MISSING) shortcut that doesn't work but still displays on the menu.

The second question is where do these files live? Github is the obvious answer. Should there be a central repo for everyone to keep their lists of does everyone do their own thing and have their own repo. Both are possible, but it's good to set a precedent at the start if you think it's important to try keep most of the lists in a central place.
