### ISSUE TITLE
[Errno 95] when launching favorites.sh with CIFS share

### ISSUE THREAD

**Issue by JosVerheij** [wizzomafizzo/MiSTer_Favorites#24]
`_Arcade` and `_@Favourites` folders are both mounted through cifs. I get the following error when running the script

```
Traceback (most recent call last):
  File "/media/fat/Scripts/favorites.sh", line 1223, in <module>
    setup_arcade_files()
  File "/media/fat/Scripts/favorites.sh", line 1208, in setup_arcade_files
    os.symlink(cores_folder, top_cores_link)
OSError: [Errno 95] Operation not supported: '/media/fat/_Arcade/cores' -> '/media/fat/_@Favourites/cores'
```

**Comment by JosVerheij** [comment]
Testing changing my sbm.conf. This is the probable cause.

**Comment by Natrox** [comment]
It's not possible to create symlinks within CIFS/SMB mounted folders. It is possible instead to use `mount --bind`, but unlike symlinks, the mount will need to be set up at every boot.

**Comment by JosVerheij** [comment]
Thanks. Might be worth to add that information to the Readme.
