### ISSUE TITLE
Arcade cores not loading

### ISSUE THREAD

**Issue by fabianPas** [wizzomafizzo/MiSTer_Favorites#4]
I have downloaded the latest version of the script and when adding Arcade cores to the favourites list and selecting the .MRA file, running it from the Favourites lists results in a quick flash of the core but MiSTer remains in the menu. The core is not loaded.

**Comment by wizzomafizzo** [comment]
Hi. Can you please let me know the folder that your .mra shortcut is in on the SD card and also if a folder/symlink called "cores" exists in this folder? Can check over ftp or ssh, might not show properly on your windows PC.

To fix this temporarily you can run `ln -s /media/fat/_Arcade/cores /media/fat/<replace the name of the folder>` but I will find out why it's not auto-generating for you

**Comment by fabianPas** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}Thank you for your reply! The symlink is there and everything is on the SD card. It seems to happen when more than one arcade favorite seems to be present. A single one seems to work. Hope this helps.                                                                                                                                                                          From: ***@***.***: July 6, 2022 02:45To: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [wizzomafizzo/MiSTer_Favorites] Arcade cores not loading (Issue #4)  
Hi. Can you please let me know the folder that your .mra shortcut is in on the SD card and also if a folder/symlink called "cores" exists in this folder? Can check over ftp or ssh, might not show properly on your windows PC.
To fix this temporarily you can run ln -s /media/fat/_Arcade/cores /media/fat/<replace the name of the folder> but I will find out why it's not auto-generating for you

**Comment by fabianPas** [comment]
I have pinpointed the issue to a more narrow situation. It seems arcade cores seems to work as long as they are added to the top level menu and not the @Favorites subdirectory. One or more cores don't seem to make a difference there. As soon as favourites get added to the @Favorites subdirectory they do not work.

**Comment by wizzomafizzo** [comment]
Thanks for looking into this more. That's interesting, it should be creating the cores symlink in that folder too. I should have time to investigate today. You can try create the symlink manually if you like with the command I mentioned earlier though

**Comment by wizzomafizzo** [comment]
@fabianPas I think I found the problem. Can you please try the latest version here on github and let me know if it's fixed things for you? It should fix itself after you run the script again or reboot

**Comment by fabianPas** [comment]
@wizzomafizzo It works perfectly fine now! Awesome. Thank you for fixing. It's a great script.
