### ISSUE TITLE
Install through downloader.ini not working

### ISSUE THREAD

**Issue by luke86** [wizzomafizzo/MiSTer_Favorites#6]
Just adding the db_url to my downloader.ini and running update_all doesnt work, looks like the file gets downloaded, checked and then removed. Not sure if it does matter but i ran the update through ssh shell

I added the following line to my downloader.ini:
```
[favorites]
db_url = https://raw.githubusercontent.com/wizzomafizzo/MiSTer_Favorites/main/favorites.json
```

Console output when i start update_all.sh:
```
SECTION: favorites

Downloading 1 files:
Scripts/favorites.sh
*.

Checking hashes...
~Removing /media/fat/Scripts/favorites.sh

Scripts/favorites.sh
*.

Checking hashes...
~Removing /media/fat/Scripts/favorites.sh

Scripts/favorites.sh
*.

Checking hashes...
~Removing /media/fat/Scripts/favorites.sh

Scripts/favorites.sh
*.

Checking hashes...
~Removing /media/fat/Scripts/favorites.sh
```

Manually downloading the script into the folder and then running update_all makes the updater write the following:
```
SECTION: favorites

Downloading 1 files:
Scripts/favorites.sh
******.

Checking hashes...
~
Scripts/favorites.sh
*.

Checking hashes...
~
Scripts/favorites.sh
*.

Checking hashes...
~
Scripts/favorites.sh
*.

Checking hashes...
~
```

**Comment by Schermobianco** [comment]
Hi, same here

**Comment by wizzomafizzo** [comment]
Hi. Can you please try the update again. I've bumped the info the the update scripts reads. It was probably out of date and getting confused by that.

**Comment by Schermobianco** [comment]
Hi @wizzomafizzo , I just tried but the issue still present, I have also tried to download manually the favorites.sh and rerun the update after a complete reboot

**Comment by luke86** [comment]
Also tried and for some reason still the same problem when running Update_all

**Comment by wizzomafizzo** [comment]
Ok one more time please. I can reproduce the problem and got it working again. If it doesn't work still give it a bit and retry, the update script may be doing some caching.

**Comment by Schermobianco** [comment]
Yes today is fine, thanks @wizzomafizzo

**Comment by luke86** [comment]
Yes now it works, thanks! I'm closing the issue.
