### ISSUE TITLE
File hash doesn't match when using downloader.

### ISSUE THREAD

**Issue by EDDIE-X** [wizzomafizzo/MiSTer_Favorites#9]
Hi,

Just to report an issue when trying to download the script via downloader:

################################################################################
SECTION: favorites

Downloading 1 files:
Scripts/favorites.sh
*.

Checking hashes...
~Bad hash on Scripts/favorites.sh (8fc0ae8bdf6cee070dc0777f86298aa7 != bb31b975a3b9e4c9adb8472811a15e63)
Removing /media/fat/Scripts/favorites.sh

Scripts/favorites.sh
*.

Checking hashes...
~Bad hash on Scripts/favorites.sh (8fc0ae8bdf6cee070dc0777f86298aa7 != bb31b975a3b9e4c9adb8472811a15e63)
Removing /media/fat/Scripts/favorites.sh

Scripts/favorites.sh
*.

Checking hashes...
~Bad hash on Scripts/favorites.sh (8fc0ae8bdf6cee070dc0777f86298aa7 != bb31b975a3b9e4c9adb8472811a15e63)
Removing /media/fat/Scripts/favorites.sh

Scripts/favorites.sh
*.

Checking hashes...
~Bad hash on Scripts/favorites.sh (8fc0ae8bdf6cee070dc0777f86298aa7 != bb31b975a3b9e4c9adb8472811a15e63)
Removing /media/fat/Scripts/favorites.sh

Seems that the favorites.json file needs to be updated:

`    "files": {
        "Scripts/favorites.sh": {
            "hash": "8fc0ae8bdf6cee070dc0777f86298aa7",
            "size": 29123,
            "url": "https://raw.githubusercontent.com/wizzomafizzo/MiSTer_Favorites/main/favorites.sh"
        }
    },`

Have a great day!

**Comment by wizzomafizzo** [comment]
Hi mate. Sorry about that, should be fixed now. Can you please let me know if it's ok
